In [3]:
%pip install pandas numpy

Collecting pandas
  Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bhimc\anaconda3\envs\venv_bike\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\bhimc\anaconda3\envs\venv_bike\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl (11.5 MB)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.26.4 pandas-2.2.2 pytz-2024.1 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
%pip install requests

Collecting requestsNote: you may need to restart the kernel to use updated packages.

  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Using cached urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2024.6.2-py3-none-any.whl.metadata (2.2 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ---------------------------------------- 0.0/64.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/64.9 kB ? eta -:--:--
   ------ --------------------------------- 10.2/64.9 kB ? eta -:--:--
   ------------------------- -------------- 41.0/64.9 kB 495.5 kB/s eta 0:00:01
   ---------------------------------------- 64.9/64.9 kB 588.0 kB/s eta 0:00:00
Downloading certifi-2024.6.2-py3-none-any.whl (164 kB)
   ---------------------------------------- 0.0/164.4 kB ? eta -:--:--
   ---------------------------------------  163.8/164.4 kB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 164.4/164.4 kB 3.3 MB/s eta 0:00:00
Using cached charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl (100 kB)
Using cached idna-3.7-py3-none-any.whl (66 kB)
Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2024.6.2 charset-normalizer-3.3.2 idna-3.7 requests-2.32.3 urllib3-2.2.1

In [5]:
import pandas as pd 
import numpy as np
import os 
import requests
import json
from datetime import datetime

In [6]:
# Create a list with all files in the folder using a list compehension

folderpath = r"C:\Users\bhimc\Documents\Work local\Bike-Sharing\Bike-Sharing-Data" # make sure to put the 'r' in front
filepaths  = [os.path.join(folderpath, name) for name in os.listdir(folderpath)]

In [7]:
filepaths

['C:\\Users\\bhimc\\Documents\\Work local\\Bike-Sharing\\Bike-Sharing-Data\\Divvy_Trips_2018_Q1.csv',
 'C:\\Users\\bhimc\\Documents\\Work local\\Bike-Sharing\\Bike-Sharing-Data\\Divvy_Trips_2018_Q2.csv',
 'C:\\Users\\bhimc\\Documents\\Work local\\Bike-Sharing\\Bike-Sharing-Data\\Divvy_Trips_2018_Q3.csv',
 'C:\\Users\\bhimc\\Documents\\Work local\\Bike-Sharing\\Bike-Sharing-Data\\Divvy_Trips_2018_Q4.csv']

In [8]:
# Read and concatenate all files simultaneously

df = pd.concat((pd.read_csv(f) for f in filepaths), ignore_index = True)

In [9]:
df.shape

(3603082, 12)

In [10]:
df.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0

In [11]:
df.tail()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
3603077,21742438,2018-12-31 23:45:17,2018-12-31 23:50:05,2931,288.0,49,Dearborn St & Monroe St,164,Franklin St & Lake St,Subscriber,Female,1983.0
3603078,21742439,2018-12-31 23:48:48,2018-12-31 23:57:22,4386,514.0,624,Dearborn St & Van Buren St (*),44,State St & Randolph St,Subscriber,Female,1990.0
3603079,21742440,2018-12-31 23:50:09,2018-12-31 23:57:16,4927,427.0,41,Federal St & Polk St,52,Michigan Ave & Lake St,Subscriber,Female,1995.0
3603080,21742441,2018-12-31 23:55:04,2018-12-31 23:58:24,1350,200.0,141,Clark St & Lincoln Ave,118,Sedgwick St & North Ave,Subscriber,Male,1999.0
3603081,21742442,2018-12-31 23:59:18,2019-01-01 00:20:43,2006,"1,285.0",260,Kedzie Ave & Milwaukee Ave,166,Ashland Ave & Wrightwood Ave,Subscriber,Male,1990.0

## Get weather data using NOAA's API

In [12]:
# Define your NOAA token - type yours in here! 

Token = 'qQyUGMkgWcFDJDFtGQdAMAwIIIMVllEY'

In [13]:
# Get the API 

r = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TAVG&limit=1000&stationid=GHCND:USW00094846&startdate=2018-01-01&enddate=2018-12-31', headers={'token':Token})

In [14]:
# Load the api response as a json

d = json.loads(r.text)

In [15]:
d

{'metadata': {'resultset': {'offset': 1, 'count': 365, 'limit': 1000}},
 'results': [{'date': '2018-01-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -189},
  {'date': '2018-01-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -191},
  {'date': '2018-01-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -114},
  {'date': '2018-01-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -139},
  {'date': '2018-01-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -152},
  {'date': '2018-01-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -148},
  {'date': '2018-01-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -84},
  {'date': '2018-01-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 9},
  {'date': '2018-01-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -6},
  {'date': '2018-01-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 27},
  {'date': '2018-01-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 131},
  {'date': '2018-01-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -48},
  {'date': '2018-01-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -106},
  {'date': '2018-01-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -112},
  {'date': '2018-01-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -72},
  {'date': '2018-01-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -92},
  {'date': '2018-01-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -104},
  {'date': '2018-01-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -60},
  {'date': '2018-01-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 1},
  {'date': '2018-01-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 40},
  {'date': '2018-01-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 46},
  {'date': '2018-01-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 84},
  {'date': '2018-01-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 19},
  {'date': '2018-01-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -19},
  {'date': '2018-01-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -4},
  {'date': '2018-01-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 50},
  {'date': '2018-01-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 84},
  {'date': '2018-01-28T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 18},
  {'date': '2018-01-29T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -26},
  {'date': '2018-01-30T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -61},
  {'date': '2018-01-31T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 14},
  {'date': '2018-02-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -23},
  {'date': '2018-02-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -118},
  {'date': '2018-02-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -32},
  {'date': '2018-02-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -34},
  {'date': '2018-02-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -145},
  {'date': '2018-02-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -112},
  {'date': '2018-02-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -85},
  {'date': '2018-02-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -104},
  {'date': '2018-02-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -47},
  {'date': '2018-02-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -73},
  {'date': '2018-02-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -69},
  {'date': '2018-02-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -93},
  {'date': '2018-02-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -67},
  {'date': '2018-02-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 1},
  {'date': '2018-02-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 49},
  {'date': '2018-02-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 21},
  {'date': '2018-02-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -41},
  {'date': '2018-02-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -27},
  {'date': '2018-02-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 57},
  {'date': '2018-02-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 149},
  {'date': '2018-02-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 1},
  {'date': '2018-02-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 7},
  {'date': '2018-02-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 43},
  {'date': '2018-02-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 23},
  {'date': '2018-02-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 47},
  {'date': '2018-02-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 47},
  {'date': '2018-02-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 90},
  {'date': '2018-02-28T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 106},
  {'date': '2018-03-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 41},
  {'date': '2018-03-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 31},
  {'date': '2018-03-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 32},
  {'date': '2018-03-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 32},
  {'date': '2018-03-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 27},
  {'date': '2018-03-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 17},
  {'date': '2018-03-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -6},
  {'date': '2018-03-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -23},
  {'date': '2018-03-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -12},
  {'date': '2018-03-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 3},
  {'date': '2018-03-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 13},
  {'date': '2018-03-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 26},
  {'date': '2018-03-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -1},
  {'date': '2018-03-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -11},
  {'date': '2018-03-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 42},
  {'date': '2018-03-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 2},
  {'date': '2018-03-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 29},
  {'date': '2018-03-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 44},
  {'date': '2018-03-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 48},
  {'date': '2018-03-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 6},
  {'date': '2018-03-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 7},
  {'date': '2018-03-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 13},
  {'date': '2018-03-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 20},
  {'date': '2018-03-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 20},
  {'date': '2018-03-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 10},
  {'date': '2018-03-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 41},
  {'date': '2018-03-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 94},
  {'date': '2018-03-28T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 71},
  {'date': '2018-03-29T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 72},
  {'date': '2018-03-30T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 38},
  {'date': '2018-03-31T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 67},
  {'date': '2018-04-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 2},
  {'date': '2018-04-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -2},
  {'date': '2018-04-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 38},
  {'date': '2018-04-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -1},
  {'date': '2018-04-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -2},
  {'date': '2018-04-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 17},
  {'date': '2018-04-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -21},
  {'date': '2018-04-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -7},
  {'date': '2018-04-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 4},
  {'date': '2018-04-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 21},
  {'date': '2018-04-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 88},
  {'date': '2018-04-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 131},
  {'date': '2018-04-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 63},
  {'date': '2018-04-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 38},
  {'date': '2018-04-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 18},
  {'date': '2018-04-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': -8},
  {'date': '2018-04-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 15},
  {'date': '2018-04-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 16},
  {'date': '2018-04-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 41},
  {'date': '2018-04-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 81},
  {'date': '2018-04-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 86},
  {'date': '2018-04-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 101},
  {'date': '2018-04-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 104},
  {'date': '2018-04-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 126},
  {'date': '2018-04-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 95},
  {'date': '2018-04-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 91},
  {'date': '2018-04-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 118},
  {'date': '2018-04-28T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 58},
  {'date': '2018-04-29T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 63},
  {'date': '2018-04-30T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 134},
  {'date': '2018-05-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 223},
  {'date': '2018-05-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 249},
  {'date': '2018-05-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 179},
  {'date': '2018-05-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 186},
  {'date': '2018-05-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 209},
  {'date': '2018-05-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 168},
  {'date': '2018-05-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 151},
  {'date': '2018-05-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 203},
  {'date': '2018-05-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 209},
  {'date': '2018-05-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 189},
  {'date': '2018-05-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 109},
  {'date': '2018-05-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 80},
  {'date': '2018-05-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 112},
  {'date': '2018-05-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 167},
  {'date': '2018-05-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 177},
  {'date': '2018-05-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 166},
  {'date': '2018-05-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 173},
  {'date': '2018-05-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 139},
  {'date': '2018-05-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 156},
  {'date': '2018-05-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 107},
  {'date': '2018-05-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 116},
  {'date': '2018-05-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 150},
  {'date': '2018-05-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 177},
  {'date': '2018-05-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 218},
  {'date': '2018-05-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 253},
  {'date': '2018-05-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',
   'value': 261},
  {'date': '2018-05-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00094846',
   'attributes': 'H,,S,',

In [16]:
# Secure all items in the response that correspond to TAVG

avg_temps = [item for item in d['results'] if item['datatype']=='TAVG']

In [18]:
# Get only the date field from all average temperature readings

dates_temp = [item['date'] for item in avg_temps]

In [19]:
# Get the temperature from all average temperature readings

temps = [item['value'] for item in avg_temps]

In [20]:
temps

[-189,
 -191,
 -114,
 -139,
 -152,
 -148,
 -84,
 9,
 -6,
 27,
 131,
 -48,
 -106,
 -112,
 -72,
 -92,
 -104,
 -60,
 1,
 40,
 46,
 84,
 19,
 -19,
 -4,
 50,
 84,
 18,
 -26,
 -61,
 14,
 -23,
 -118,
 -32,
 -34,
 -145,
 -112,
 -85,
 -104,
 -47,
 -73,
 -69,
 -93,
 -67,
 1,
 49,
 21,
 -41,
 -27,
 57,
 149,
 1,
 7,
 43,
 23,
 47,
 47,
 90,
 106,
 41,
 31,
 32,
 32,
 27,
 17,
 -6,
 -23,
 -12,
 3,
 13,
 26,
 -1,
 -11,
 42,
 2,
 29,
 44,
 48,
 6,
 7,
 13,
 20,
 20,
 10,
 41,
 94,
 71,
 72,
 38,
 67,
 2,
 -2,
 38,
 -1,
 -2,
 17,
 -21,
 -7,
 4,
 21,
 88,
 131,
 63,
 38,
 18,
 -8,
 15,
 16,
 41,
 81,
 86,
 101,
 104,
 126,
 95,
 91,
 118,
 58,
 63,
 134,
 223,
 249,
 179,
 186,
 209,
 168,
 151,
 203,
 209,
 189,
 109,
 80,
 112,
 167,
 177,
 166,
 173,
 139,
 156,
 107,
 116,
 150,
 177,
 218,
 253,
 261,
 282,
 282,
 248,
 241,
 249,
 216,
 153,
 192,
 192,
 194,
 161,
 219,
 179,
 189,
 181,
 178,
 207,
 237,
 228,
 236,
 271,
 299,
 303,
 216,
 206,
 188,
 169,
 201,
 226,
 205,
 229,
 227,
 246,
 278,
 306,
 295,
 250,
 254,
 286,
 274,
 233,
 214,
 238,
 263,
 278,
 251,
 259,
 277,
 257,
 268,
 279,
 248,
 223,
 243,
 243,
 219,
 215,
 224,
 239,
 260,
 248,
 212,
 218,
 222,
 225,
 227,
 229,
 249,
 251,
 278,
 293,
 253,
 241,
 233,
 255,
 245,
 249,
 259,
 251,
 262,
 266,
 252,
 238,
 241,
 242,
 239,
 221,
 208,
 211,
 202,
 216,
 271,
 297,
 279,
 220,
 198,
 211,
 247,
 266,
 251,
 263,
 281,
 203,
 195,
 193,
 179,
 183,
 194,
 216,
 206,
 228,
 231,
 245,
 261,
 229,
 208,
 241,
 261,
 148,
 154,
 182,
 227,
 161,
 148,
 146,
 102,
 137,
 160,
 167,
 209,
 188,
 141,
 176,
 144,
 208,
 246,
 227,
 102,
 47,
 49,
 80,
 66,
 63,
 87,
 72,
 97,
 87,
 30,
 89,
 96,
 65,
 66,
 91,
 95,
 84,
 83,
 108,
 119,
 103,
 67,
 57,
 89,
 89,
 87,
 35,
 18,
 12,
 -39,
 3,
 6,
 -41,
 -41,
 -6,
 12,
 10,
 6,
 -24,
 -2,
 1,
 11,
 43,
 72,
 36,
 -11,
 -47,
 -57,
 -12,
 10,
 32,
 52,
 13,
 -8,
 -21,
 -7,
 -63,
 -43,
 -43,
 -49,
 -13,
 11,
 3,
 38,
 18,
 17,
 26,
 5,
 39,
 65,
 16,
 -12,
 4,
 -18,
 9,
 13,
 56,
 55,
 -18,
 -36,
 13]

In [21]:
# Put the results in a dataframe

df_temp = pd.DataFrame()

In [22]:
# Get only date and cast it to date time; convert temperature from tenths of Celsius to normal Celsius

df_temp['date'] = [datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in dates_temp]
df_temp['avgTemp'] = [float(v)/10.0 for v in temps]

In [23]:
df_temp.tail()

          date  avgTemp
360 2018-12-27      5.6
361 2018-12-28      5.5
362 2018-12-29     -1.8
363 2018-12-30     -3.6
364 2018-12-31      1.3

In [24]:
df_temp.head()

        date  avgTemp
0 2018-01-01    -18.9
1 2018-01-02    -19.1
2 2018-01-03    -11.4
3 2018-01-04    -13.9
4 2018-01-05    -15.2

In [25]:
df.dtypes

trip_id                int64
start_time            object
end_time              object
bikeid                 int64
tripduration          object
from_station_id        int64
from_station_name     object
to_station_id          int64
to_station_name       object
usertype              object
gender                object
birthyear            float64
dtype: object

In [27]:
df['start_time'] = pd.to_datetime(df['start_time'], dayfirst = True)

ValueError: time data "2018-01-13 00:01:48" doesn't match format "%Y-%d-%m %H:%M:%S", at position 34034. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [28]:
df['start_time'].replace(['', 'NaN', 'invalid_date'], pd.NaT, inplace=True)

In [29]:
# Convert to datetime with error handling
df['start_time'] = pd.to_datetime(df['start_time'], dayfirst=True, errors='coerce')

In [30]:
df['date'] = pd.to_datetime(df['start_time'], format='%Y-%m-%d').dt.date

In [31]:
df['date'] = pd.to_datetime(df['date'])

In [32]:
df_temp.head()

        date  avgTemp
0 2018-01-01    -18.9
1 2018-01-02    -19.1
2 2018-01-03    -11.4
3 2018-01-04    -13.9
4 2018-01-05    -15.2

In [33]:
%%time
df_merged = df.merge(df_temp, how = 'left', on = 'date', indicator = True)

CPU times: total: 5.52 s
Wall time: 13 s

In [34]:
df_merged.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,date,avgTemp,_merge
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0,2018-01-01,-18.9,both
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0,2018-01-01,-18.9,both
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0,2018-01-01,-18.9,both
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0,2018-01-01,-18.9,both
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0,2018-01-01,-18.9,both

In [35]:
df_merged['_merge'].value_counts(dropna = False)

_merge
left_only     2202593
both          1400489
right_only          0
Name: count, dtype: int64